services:
  db_test:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_PASSWORD=password_test
      - POSTGRES_DB=refacil_db_test 
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 3  
