
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - refacil-network
    #command: >
    #  sh -c "npm run migration:run && npm start"
  db:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=refacil_db
    ports:
      - "5435:5432"
    networks:
      - refacil-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  refacil-network:
volumes:
  pgdata:
